type NoteAssetDirectory = "ingredients" | "accords" | "families" | "root";

type NoteAssetConfig = {
  file: string;
  directory: NoteAssetDirectory;
  toneClassName: string;
};

function normalizeNoteLabel(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const TONES = {
  amber: "from-[#f6e2b8] via-[#f8efe0] to-[#fffaf2]",
  aromatic: "from-[#dde9db] via-[#eef5ec] to-[#fbfdfb]",
  berry: "from-[#efd7e6] via-[#f8eef4] to-[#fffafc]",
  bold: "from-[#e7d6ce] via-[#f4ebe6] to-[#fcf8f6]",
  clean: "from-[#f1f0ec] via-[#faf8f4] to-[#fffdfb]",
  citrus: "from-[#f9edbc] via-[#fcf6dd] to-[#fffdf3]",
  floral: "from-[#f7dde2] via-[#fdf0f2] to-[#fffafb]",
  fresh: "from-[#d6eedf] via-[#edf8f1] to-[#fbfefa]",
  marine: "from-[#d7ecf3] via-[#edf8fb] to-[#fbfeff]",
  passionate: "from-[#efd4dc] via-[#f9edf1] to-[#fffafd]",
  powdery: "from-[#f2e8ea] via-[#fbf4f5] to-[#fffafb]",
  powerful: "from-[#ead5ca] via-[#f6ebe4] to-[#fdf9f7]",
  soft: "from-[#ebe5dd] via-[#f5f1ec] to-[#fcfaf8]",
  spice: "from-[#f3dfcf] via-[#fbefe6] to-[#fffaf6]",
  sweet: "from-[#f7e6dd] via-[#fdf2ed] to-[#fffaf7]",
  vanilla: "from-[#f6e2b8] via-[#f8efe0] to-[#fffaf2]",
  vintage: "from-[#efe4d8] via-[#f8f1ea] to-[#fdfaf7]",
  warm: "from-[#f4ddd1] via-[#fbefe8] to-[#fff9f6]",
  woody: "from-[#ead8c9] via-[#f5ece5] to-[#fcfaf8]",
} as const;

function createAsset(file: string, directory: NoteAssetDirectory, toneClassName: string): NoteAssetConfig {
  return { file, directory, toneClassName };
}

const NOTE_ASSET_CONFIG: Record<string, NoteAssetConfig> = {
  amber: createAsset("amber", "root", TONES.amber),
  aromatic: createAsset("aromatic", "root", TONES.aromatic),
  bold: createAsset("bold", "root", TONES.bold),
  clean: createAsset("clean", "root", TONES.clean),
  citrus: createAsset("citrus", "root", TONES.citrus),
  floral: createAsset("floral", "root", TONES.floral),
  fresh: createAsset("fresh", "root", TONES.fresh),
  fruity: createAsset("fruity", "root", TONES.berry),
  marine: createAsset("marine", "root", TONES.marine),
  passionate: createAsset("passionate", "root", TONES.passionate),
  powdery: createAsset("powdery", "root", TONES.powdery),
  powerful: createAsset("powerful", "root", TONES.powerful),
  spicy: createAsset("spicy", "root", TONES.spice),
  sweet: createAsset("sweet", "root", TONES.sweet),
  vanilla: createAsset("vanilla", "root", TONES.vanilla),
  vintage: createAsset("vintage", "root", TONES.vintage),
  warm: createAsset("warm", "root", TONES.warm),
  woody: createAsset("woody", "root", TONES.woody),
  almond: createAsset("almond", "ingredients", TONES.soft),
  "amalfi-lemon": createAsset("amalfi-lemon", "ingredients", TONES.citrus),
  apple: createAsset("apple", "ingredients", TONES.fresh),
  basil: createAsset("basil", "ingredients", TONES.aromatic),
  bergamot: createAsset("bergamot", "ingredients", TONES.citrus),
  "bitter-almond": createAsset("bitter-almond", "ingredients", TONES.soft),
  "black-basil": createAsset("black-basil", "ingredients", TONES.aromatic),
  "black-currant": createAsset("black-currant", "ingredients", TONES.berry),
  blackberry: createAsset("blackberry", "ingredients", TONES.berry),
  "blood-orange": createAsset("blood-orange", "ingredients", TONES.citrus),
  "brazilian-redwood": createAsset("brazilian-redwood", "ingredients", TONES.woody),
  cacao: createAsset("cacao", "ingredients", TONES.warm),
  cardamom: createAsset("cardamom", "ingredients", TONES.aromatic),
  "cashmere-wood": createAsset("cashmere-wood", "ingredients", TONES.woody),
  cedarwood: createAsset("cedarwood", "ingredients", TONES.woody),
  cinnamon: createAsset("cinnamon", "ingredients", TONES.warm),
  clove: createAsset("clove", "ingredients", TONES.spice),
  coffee: createAsset("coffee", "ingredients", TONES.warm),
  cucumber: createAsset("cucumber", "ingredients", TONES.fresh),
  cyclamen: createAsset("cyclamen", "ingredients", TONES.floral),
  davana: createAsset("davana", "ingredients", TONES.warm),
  elemi: createAsset("elemi", "ingredients", TONES.amber),
  "fig-milk": createAsset("fig-milk", "ingredients", TONES.soft),
  freesia: createAsset("freesia", "ingredients", TONES.floral),
  geranium: createAsset("geranium", "ingredients", TONES.floral),
  ginger: createAsset("ginger", "ingredients", TONES.spice),
  jasmine: createAsset("jasmine", "ingredients", TONES.floral),
  "juniper-berry": createAsset("juniper-berry", "ingredients", TONES.aromatic),
  lavender: createAsset("lavender", "ingredients", TONES.floral),
  lemon: createAsset("lemon", "ingredients", TONES.citrus),
  licorice: createAsset("licorice", "ingredients", TONES.warm),
  "mandarin-orange": createAsset("mandarin-orange", "ingredients", TONES.citrus),
  melon: createAsset("melon", "ingredients", TONES.fresh),
  mint: createAsset("mint", "ingredients", TONES.fresh),
  oakmoss: createAsset("oakmoss", "ingredients", TONES.aromatic),
  "orange-blossom": createAsset("orange-blossom", "ingredients", TONES.floral),
  orris: createAsset("orris", "ingredients", TONES.floral),
  osmanthus: createAsset("osmanthus", "ingredients", TONES.floral),
  patchouli: createAsset("patchouli", "ingredients", TONES.woody),
  pear: createAsset("pear", "ingredients", TONES.fresh),
  pepper: createAsset("pepper", "ingredients", TONES.spice),
  pimento: createAsset("pimento", "ingredients", TONES.spice),
  "pine-needles": createAsset("pine-needles", "ingredients", TONES.aromatic),
  "pink-pepper": createAsset("pink-pepper", "ingredients", TONES.spice),
  praline: createAsset("praline", "ingredients", TONES.sweet),
  raspberry: createAsset("raspberry", "ingredients", TONES.berry),
  rose: createAsset("rose", "ingredients", TONES.floral),
  sage: createAsset("sage", "ingredients", TONES.aromatic),
  sandalwood: createAsset("sandalwood", "ingredients", TONES.woody),
  "sicilian-lemon": createAsset("sicilian-lemon", "ingredients", TONES.citrus),
  "sour-cherry": createAsset("sour-cherry", "ingredients", TONES.berry),
  strawberry: createAsset("strawberry", "ingredients", TONES.berry),
  "sweet-lime": createAsset("sweet-lime", "ingredients", TONES.citrus),
  "tonka-bean": createAsset("tonka-bean", "ingredients", TONES.vanilla),
  tuberose: createAsset("tuberose", "ingredients", TONES.floral),
  vetiver: createAsset("vetiver", "ingredients", TONES.aromatic),
  violet: createAsset("violet", "ingredients", TONES.floral),
  "amber-resin": createAsset("amber", "accords", TONES.amber),
  "airy-dry-down": createAsset("airy-dry-down", "accords", TONES.clean),
  "amber-woods": createAsset("amber-woods", "accords", TONES.amber),
  ambroxan: createAsset("ambroxan", "accords", TONES.soft),
  cashmeran: createAsset("cashmeran", "accords", TONES.soft),
  "clary-sage": createAsset("clary-sage", "accords", TONES.aromatic),
  "clean-green-notes": createAsset("clean-green-notes", "accords", TONES.fresh),
  "dry-soft-amber": createAsset("dry-soft-amber", "accords", TONES.amber),
  "green-apple": createAsset("green-apple", "accords", TONES.fresh),
  musk: createAsset("musk", "accords", TONES.soft),
  "oud-accord": createAsset("oud-accord", "accords", TONES.woody),
  "pearl-accord": createAsset("pearl-accord", "accords", TONES.clean),
  "powdery-florals": createAsset("powdery-florals", "accords", TONES.powdery),
  "rum-accord": createAsset("rum-accord", "accords", TONES.warm),
  "saffron-glow": createAsset("saffron-glow", "accords", TONES.warm),
  "smoky-warm": createAsset("smoky-warm", "accords", TONES.warm),
  "smooth-balsamic-warmth": createAsset("smooth-balsamic-warmth", "accords", TONES.warm),
  "soft-smoke": createAsset("soft-smoke", "accords", TONES.soft),
  suede: createAsset("suede", "accords", TONES.soft),
  "warm-spice": createAsset("warm-spice", "accords", TONES.spice),
  "watery-accord": createAsset("watery-accord", "accords", TONES.marine),
  "watery-green": createAsset("watery-green", "accords", TONES.fresh),
  "white-floral": createAsset("white-floral", "accords", TONES.floral),
  "white-musk": createAsset("white-musk", "accords", TONES.clean),
};

const RAW_NOTE_ALIASES: Record<string, string> = {
  amber: "amber",
  "amber accord": "amber",
  "amber resin": "amber-resin",
  "amber woods": "amber-woods",
  almond: "almond",
  "amalfi lemon": "amalfi-lemon",
  apple: "apple",
  aromatic: "aromatic",
  "atlas cedar": "cedarwood",
  basil: "basil",
  bergamot: "bergamot",
  "bitter almond": "bitter-almond",
  "black basil": "black-basil",
  "black currant": "black-currant",
  blackberry: "blackberry",
  "blood orange": "blood-orange",
  "brazilian redwood": "brazilian-redwood",
  "bulgarian rose": "rose",
  cacao: "cacao",
  cardamom: "cardamom",
  cashmeran: "cashmeran",
  "cashmere wood": "cashmere-wood",
  cedar: "cedarwood",
  cedarwood: "cedarwood",
  clean: "clean",
  "clean air accord": "clean",
  "clean musk": "white-musk",
  coffee: "coffee",
  cinnamon: "cinnamon",
  citrus: "citrus",
  "citrus accord": "citrus",
  "citrus peel": "citrus",
  clove: "clove",
  cucumber: "cucumber",
  "cucumber water": "cucumber",
  cyclamen: "cyclamen",
  davana: "davana",
  "dark woods": "woody",
  "dry woods": "woody",
  elemi: "elemi",
  "fig milk": "fig-milk",
  floral: "floral",
  "fresh melon": "melon",
  fresh: "fresh",
  freesia: "freesia",
  "french lavender": "lavender",
  geranium: "geranium",
  "green apple": "green-apple",
  "green pear": "pear",
  ginger: "ginger",
  "iris petal": "orris",
  jasmine: "jasmine",
  "jasmine accord": "jasmine",
  "jasmine sambac": "jasmine",
  "juniper berry": "juniper-berry",
  lavender: "lavender",
  lemon: "lemon",
  licorice: "licorice",
  "light cotton musk": "white-musk",
  "light woods": "woody",
  "madagascar vanilla": "vanilla",
  "mandarin orange": "mandarin-orange",
  melon: "melon",
  mint: "mint",
  musk: "musk",
  oakmoss: "oakmoss",
  "orange blossom": "orange-blossom",
  "african orange flower": "orange-blossom",
  "airy dry-down": "airy-dry-down",
  orris: "orris",
  osmanthus: "osmanthus",
  "oud accord": "oud-accord",
  patchouli: "patchouli",
  pear: "pear",
  "pearl accord": "pearl-accord",
  pepper: "pepper",
  pimento: "pimento",
  "pine needles": "pine-needles",
  "pink pepper": "pink-pepper",
  powdery: "powdery",
  "powdery florals": "powdery-florals",
  praline: "praline",
  passionate: "passionate",
  powerful: "powerful",
  sandalwood: "sandalwood",
  raspberry: "raspberry",
  rose: "rose",
  rum: "rum-accord",
  "rum accord": "rum-accord",
  sage: "sage",
  "sicilian lemon": "sicilian-lemon",
  "saffron glow": "saffron-glow",
  "smoky warm": "smoky-warm",
  "smooth balsamic warmth": "smooth-balsamic-warmth",
  "soft smoke": "soft-smoke",
  "smooth musk": "white-musk",
  "soft citrus peel": "citrus",
  "soft violet": "violet",
  "sour cherry": "sour-cherry",
  spicy: "spicy",
  strawberry: "strawberry",
  suede: "suede",
  "sweet lime": "sweet-lime",
  sweet: "sweet",
  "tonka bean": "tonka-bean",
  tonka: "tonka-bean",
  tuberose: "tuberose",
  vanilla: "vanilla",
  vetiver: "vetiver",
  vintage: "vintage",
  violet: "violet",
  "virginia cedar": "cedarwood",
  "virginian cedar": "cedarwood",
  "velvet musk": "white-musk",
  warm: "warm",
  "warm spice": "warm-spice",
  "warm vanilla": "vanilla",
  "watery accord": "watery-accord",
  "watery green": "watery-green",
  "white musk": "white-musk",
  "white floral": "white-floral",
  "white woods": "woody",
  woody: "woody",
  "woodsy notes": "woody",
  "woody notes": "woody",
  fruity: "fruity",
  marine: "marine",
  "marine notes": "marine",
  "clean green notes": "clean-green-notes",
  "dry soft amber": "dry-soft-amber",
  bold: "bold",
};

const NOTE_ALIASES = Object.fromEntries(
  Object.entries(RAW_NOTE_ALIASES).map(([key, value]) => [normalizeNoteLabel(key), value]),
) as Record<string, string>;

export type NoteVisual = {
  key: string;
  src: string;
  toneClassName: string;
};

export function getNoteVisual(label: string): NoteVisual | null {
  const normalized = normalizeNoteLabel(label);
  const resolvedKey = NOTE_ALIASES[normalized] ?? normalized;
  const asset = NOTE_ASSET_CONFIG[resolvedKey];

  if (!asset) {
    return null;
  }

  return {
    key: resolvedKey,
    src: asset.directory === "root"
      ? `/note-illustrations/${asset.file}.png`
      : `/note-illustrations/${asset.directory}/${asset.file}.png`,
    toneClassName: asset.toneClassName,
  };
}
